apiVersion: v1
kind: Service
metadata:
  name: carbon-extender
  namespace: carbon-scheduler
spec:
  selector:
    app: carbon-extender
  ports:
    - port: 8080
      targetPort: 8080
      name: http