apiVersion: v1
kind: COnfigMap
metadata:
  name: carbon-extender-scores
  namespace: carbon-scheduler
data:
  scores.json: |
    {
      "iict-mv545-greenschedk8s-wk2": 10,
      "iict-mv546-greenschedk8s-wk1": 0
    }