apiVersion: v1
kind: ConfigMap
metadata:
  name: carbon-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: carbon-aware
    extenders:
      - urlPrefix: "http://carbon-extender.carbon-scheduler.svc.cluster.local:8080"
        prioritizeVerb: "prioritize"
        filterVerb: "filter"
        weight: 100
        enableHTTPS: false
        nodeCacheCapable: false
        ignorable: true
