apiVersion: v1
kind: ServiceAccount
metadata:
  name: carbon-extender
  namespace: carbon-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carbon-extender
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carbon-extender
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carbon-extender
subjects:
  - kind: ServiceAccount
    name: carbon-extender
    namespace: carbon-scheduler
