apiVersion: v1
kind: Service
metadata:
  name: carbon-extender
  namespace: carbon-scheduler
  labels:
    app: carbon-extender
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: carbon-extender
  ports:
    - port: 8080
      targetPort: 8080
      name: http
