apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: carbon-extender
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - carbon-scheduler
  selector:
    matchLabels:
      app: carbon-extender
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
