apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-extender
  namespace: carbon-scheduler
  labels:
    app: carbon-extender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbon-extender
  template:
    metadata:
      labels:
        app: carbon-extender
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: extender
          image: ghcr.io/kevinauberson/k8s-carbon-aware-scheduler-extender/extender:sha-c4bd63f3bd3ee03ef2289ee0c78adfd118fbccfa
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SIGNAL_FILE
              value: /etc/carbon-signal/signal.json
          volumeMounts:
            - name: carbon-signal
              mountPath: /etc/carbon-signal
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: carbon-signal
          configMap:
            name: carbon-signal
