apiVersion: v1
kind: Pod
metadata:
  name: demo-1
  labels:
    demo: carbon
spec:
  schedulerName: carbon-aware
  containers:
    - name: sleeper
      image: busybox
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-2
  labels:
    demo: carbon
spec:
  schedulerName: carbon-aware
  containers:
    - name: sleeper
      image: busybox
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-3
  labels:
    demo: carbon
spec:
  schedulerName: carbon-aware
  containers:
    - name: sleeper
      image: busybox
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-4
  labels:
    demo: carbon
spec:
  schedulerName: carbon-aware
  containers:
    - name: sleeper
      image: busybox
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-5
  labels:
    demo: carbon
spec:
  schedulerName: carbon-aware
  containers:
    - name: sleeper
      image: busybox
      command: ["sleep", "3600"]
