apiVersion: v1
kind: Pod
metadata:
  name: demo-latency
  labels:
    carbon-class: latency-sensitive
spec:
  schedulerName: carbon-aware
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]